force-app/main/default/objects/Region__c/Region__c.object-meta.xml
<CustomObject>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Region__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <description>CBSA Code Number</description>
    <label>CBSA Code</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Region_Assignment__c/Region_Assignment__c.object-meta.xml
<CustomObject>
    <label>Region Assignment</label>
    <nameField>
        <displayFormat>RA-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Region Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Region_Assignment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Region Assignments</relationshipLabel>
    <relationshipName>Region_Assignments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Region_Assignment__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <referenceTo>Region__c</referenceTo>
    <relationshipLabel>Region Assignments</relationshipLabel>
    <relationshipName>Region_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/Region_AssignmentTest.cls
@isTest
public with sharing class Region_AssignmentTest {
   
    @TestSetup
    static void makeData(){
        Account newAccount = new Account(Name = 'Test');
        insert newAccount;

        Region__c region = new Region__c(Name = 'Test', Code__c = '123');
        insert region;
    } 

    @IsTest
    static void methodName(){
        Account newAccount = [Select id From Account WHERE Name = 'Test' Limit 1];
        Region__c region = [Select id From Region__c WHERE Code__c = '123' Limit 1];

        Test.startTest();
            Region_Assignment__c regionAssignment = new Region_Assignment__c();
            regionAssignment.Account__c = newAccount.id;
            regionAssignment.Region__c = region.id;
            insert regionAssignment;

            System.assert(regionAssignment.id != null, 'Pass');
            
        Test.stopTest();
        
    } 
}