force-app/main/default/objects/Region__c/Region__c.object-meta.xml
<CustomObject>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Region_Assignment__c/Region_Assignment__c.object-meta.xml
<CustomObject>
    <label>Region Assignment</label>
    <nameField>
        <displayFormat>RA-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Region Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Region_Assignment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Region Assignments</relationshipLabel>
    <relationshipName>Region_Assignments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Region_Assignment__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <referenceTo>Region__c</referenceTo>
    <relationshipLabel>Region Assignments</relationshipLabel>
    <relationshipName>Region_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/Region_Assignment.cls
public without sharing class Region_Assignment extends fflib_SObjectDomain{
    
    public Region_Assignment(List<Region_Assignment__c> sObjectList) {
        super(sObjectList);
    }
    
    public override void onBeforeInsert() {
        set<Id> listAccountId = new set<Id>();

        for(Region_Assignment__c item : (List<Region_Assignment__c>) Records){
            listAccountId.add(item.Account__c);   
        }

        map<String, String> mapExistingRegions = new map<String, String>();
        for(Region_Assignment__c item : new Region_AssignmentSelector().selectBySetAccountId(listAccountId)){
            mapExistingRegions.put(item.Account__c + '-' + item.Region__c, item.Region__r.Name);
        }

        for(Region_Assignment__c item : (List<Region_Assignment__c>) Records){
            if (mapExistingRegions.containsKey(item.Account__c + '-' + item.Region__c)) {
                item.addError(Label.DuplicateRegionAssignment.replace('{RegionName}', mapExistingRegions.get(item.Account__c + '-' + item.Region__c)));    
            }
        }
    }
    
}