force-app/main/default/objects/Service_Template__c/Service_Template__c.object-meta.xml
<CustomObject>
    <label>Service Template</label>
    <nameField>
        <label>Service Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Template__c/fields/AFM_Zone__c.field-meta.xml
<CustomField>
    <fullName>AFM_Zone__c</fullName>
    <label>AFM Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>AFM_Zone</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Template__c/fields/Frequency_Factor__c.field-meta.xml
<CustomField>
    <fullName>Frequency_Factor__c</fullName>
    <label>Frequency Factor</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Service_Template__c/fields/Service_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Service_Schedule__c</fullName>
    <label>Service Schedule</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Template__c/fields/Service_Template_External_ID__c.field-meta.xml
<CustomField>
    <fullName>Service_Template_External_ID__c</fullName>
    <externalId>true</externalId>
    <label>Service Template External ID</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Service_Template__c/fields/Service_Template_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Template_Type__c</fullName>
    <label>Service Template Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Service_Template_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Template__c/fields/Total_Services__c.field-meta.xml
<CustomField>
    <fullName>Total_Services__c</fullName>
    <label>Total Services</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/AFM_Zone.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>A</fullName>
    </customValue>
    <customValue>
        <fullName>B</fullName>
    </customValue>
    <customValue>
        <fullName>C</fullName>
    </customValue>
    <customValue>
        <fullName>D</fullName>
    </customValue>
    <customValue>
        <fullName>E</fullName>
    </customValue>
    <customValue>
        <fullName>F</fullName>
    </customValue>
    <masterLabel>AFM Zone</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Service_Template_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AFM Weekly Lawncare</fullName>
    </customValue>
    <customValue>
        <fullName>AFM Bi-weekly Lawncare</fullName>
        <label>AFM Bi-weekly Landscaping</label>
    </customValue>
    <customValue>
        <fullName>AFM Monthly Lawncare</fullName>
    </customValue>
    <customValue>
        <fullName>AFM Weekly Cleaning</fullName>
    </customValue>
    <customValue>
        <fullName>AFM Bi-weekly Cleaning</fullName>
    </customValue>
    <customValue>
        <fullName>AFM Monthly Cleaning</fullName>
    </customValue>
    <customValue>
        <fullName>One-Time</fullName>
    </customValue>
    <customValue>
        <fullName>Custom</fullName>
    </customValue>
    <customValue>
        <fullName>MSR Premium Refresh</fullName>
    </customValue>
    <masterLabel>Service Template Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ServiceTemplateSelector.cls
/*
    Created by: Fran Oseguer
    Description: Selector for Service_Template__c object
*/
public without sharing class ServiceTemplateSelector extends fflib_SObjectSelector{
    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField> {
            Service_Template__c.Id,
            Service_Template__c.AFM_Zone__c,
            Service_Template__c.Frequency_Factor__c,
            Service_Template__c.Service_Schedule__c,
            Service_Template__c.Service_Template_External_ID__c,
            Service_Template__c.Name,
            Service_Template__c.Service_Template_Type__c,
            Service_Template__c.Total_Services__c
        };
    }
    
    public Schema.SObjectType getSObjectType() {
        return Service_Template__c.sObjectType;
    }
    
    public Map<String, List<Service_Template__c>> selectByType(set<String> setTemplateType) {
        Map<String, List<Service_Template__c>> mapTemplatesByType = new Map<String, List<Service_Template__c>>();

        for(Service_Template__c item : Database.query(newQueryFactory().setCondition('Service_Template_Type__c IN: setTemplateType').toSOQL()))
        {
            List<Service_Template__c> listTemplate = new List<Service_Template__c>();
            if (mapTemplatesByType.containsKey(item.Service_Template_Type__c)) {
                listTemplate = mapTemplatesByType.get(item.Service_Template_Type__c);    
            }
            listTemplate.add(item);
            mapTemplatesByType.put(item.Service_Template_Type__c, listTemplate);
        }
        
        return mapTemplatesByType;
    }
}