force-app/main/default/objects/Asset/fields/External_ID__c.field-meta.xml
<CustomField>
    <fullName>External_ID__c</fullName>
    <externalId>true</externalId>
    <label>TE External ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Asset/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Region</label>
    <referenceTo>Region__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Component_Service__c/Component_Service__c.object-meta.xml
<CustomObject>
    <label>Component Service</label>
    <nameField>
        <displayFormat>CS-{00000}</displayFormat>
        <label>Component Service Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Component Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Component_Service__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Component Services</relationshipLabel>
    <relationshipName>Component_Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Component_Service__c/fields/Service_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Type</label>
    <referenceTo>Service_Type__c</referenceTo>
    <relationshipLabel>Component Services</relationshipLabel>
    <relationshipName>Component_Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The specific client to whom this bundle/package is available.</inlineHelpText>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Client_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Is_Customer_Accessible__c.field-meta.xml
<CustomField>
    <fullName>Is_Customer_Accessible__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Customer Accessible</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Merchandising_Tags__c.field-meta.xml
<CustomField>
    <fullName>Merchandising_Tags__c</fullName>
    <label>Product Categories</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Most Popular</fullName>
            </value>
            <value>
                <fullName>Best Value</fullName>
            </value>
            <value>
                <fullName>Garden Beds</fullName>
            </value>
            <value>
                <fullName>Seasonal Cleanup</fullName>
            </value>
            <value>
                <fullName>Trees &amp; Bushes</fullName>
            </value>
            <value>
                <fullName>Landscaping</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Photo_URL__c.field-meta.xml
<CustomField>
    <fullName>Product_Photo_URL__c</fullName>
    <label>Product Photo URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Product2/fields/TE_Regions__c.field-meta.xml
<CustomField>
    <fullName>TE_Regions__c</fullName>
    <label>TE Regions</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TE_Regions</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Region__c/Region__c.object-meta.xml
<CustomObject>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Type__c/Service_Type__c.object-meta.xml
<CustomObject>
    <label>Service Type</label>
    <nameField>
        <label>Service Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Type__c/fields/Contractor_Description__c.field-meta.xml
<CustomField>
    <fullName>Contractor_Description__c</fullName>
    <label>Contractor Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Service_Type__c/fields/Customer_Description__c.field-meta.xml
<CustomField>
    <fullName>Customer_Description__c</fullName>
    <label>Customer Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/globalValueSets/TE_Regions.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Abbeville</fullName>
    </customValue>
    <customValue>
        <fullName>Aberdeen</fullName>
    </customValue>
    <customValue>
        <fullName>Abilene</fullName>
    </customValue>
    <customValue>
        <fullName>Ada</fullName>
    </customValue>
    <customValue>
        <fullName>Adjuntas</fullName>
    </customValue>
    <customValue>
        <fullName>Adrian</fullName>
    </customValue>
    <customValue>
        <fullName>Aguadilla-Isabela</fullName>
    </customValue>
    <customValue>
        <fullName>Akron</fullName>
    </customValue>
    <customValue>
        <fullName>Alamogordo</fullName>
    </customValue>
    <customValue>
        <fullName>Albany</fullName>
    </customValue>
    <customValue>
        <fullName>Albany-Schenectady-Troy</fullName>
    </customValue>
    <customValue>
        <fullName>Albemarle</fullName>
    </customValue>
    <customValue>
        <fullName>Albert Lea</fullName>
    </customValue>
    <customValue>
        <fullName>Albertville</fullName>
    </customValue>
    <customValue>
        <fullName>Albuquerque</fullName>
    </customValue>
    <customValue>
        <fullName>Alexander City</fullName>
    </customValue>
    <customValue>
        <fullName>Alexandria</fullName>
    </customValue>
    <customValue>
        <fullName>Alice</fullName>
    </customValue>
    <customValue>
        <fullName>Allegan</fullName>
    </customValue>
    <customValue>
        <fullName>Allentown-Bethlehem-Easton</fullName>
    </customValue>
    <customValue>
        <fullName>Alma</fullName>
    </customValue>
    <customValue>
        <fullName>Alpena</fullName>
    </customValue>
    <customValue>
        <fullName>Altoona</fullName>
    </customValue>
    <customValue>
        <fullName>Altus</fullName>
    </customValue>
    <customValue>
        <fullName>Amarillo</fullName>
    </customValue>
    <customValue>
        <fullName>Americus</fullName>
    </customValue>
    <customValue>
        <fullName>Ames</fullName>
    </customValue>
    <customValue>
        <fullName>Amsterdam</fullName>
    </customValue>
    <customValue>
        <fullName>Anchorage</fullName>
    </customValue>
    <customValue>
        <fullName>Anderson</fullName>
    </customValue>
    <masterLabel>TE Regions</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OrderFunnel_ProductUtility.cls
public with sharing class OrderFunnel_ProductUtility {

    public static List<OrderFunnel_Models.ProductSearchResultModel> searchProducts(String accountId, String assetId, Boolean includeInternal, List<String> tags){

        String region = null;

        if(assetId != null && assetId != ''){
            List<Asset> assets = OrderFunnel_AssetUtility.getAssets(null, null, assetId, false);
            accountId = assets[0].AccountId;
            region = assets[0]?.Region__r?.TE_Region__c;
        }

        String query = buildSearchQuery(accountId, region, includeInternal, tags);
        List<Product2> products = Database.query(query);

        List<OrderFunnel_Models.ProductSearchResultModel> models = new List<OrderFunnel_Models.ProductSearchResultModel>();

        for(Product2 prod:products){
            models.add(buildSearchModel(prod));
        }

        return models;
    }

    private static String buildSearchQuery(String accountId, String region, Boolean includeInternal, List<String> tags){
        String query = 'SELECT Id, ProductCode, Name, Display_Name__c, RecordType.Name, ';
        query += 'Description, Merchandising_Tags__c, Family, Client__c, External_ID__c, Product_Photo_URL__c,';

        query += '(SELECT Id, Service_Type__c, Service_Type__r.Name, Service_Type__r.Contractor_Description__c, Service_Type__r.Customer_Description__c ';
        query += 'FROM Component_Services__r) ';

        query += 'FROM Product2 ';
        query += 'WHERE ';

        query += '(Client__c = null OR ';
        if(accountId != null && accountId != ''){
            query += 'Client__c = :accountId';
        }
        query = query.removeEnd(' OR ');
        query += ') AND ';

        if(includeInternal == false){
            query += 'Is_Customer_Accessible__c = true AND ';
        }

        if(tags.isEmpty() == false){
            query += 'Merchandising_Tags__c INCLUDES (\'' + String.join(tags,'\',\'') + '\') AND ';
        }

        // query += '(Regional_Availability__c = \'All\' OR ';
        // if(region != null){
        //     query += '(Regional_Availability__c = \'Exclude\' AND TE_Regions__c EXCLUDES (\'' + region + '\')) OR ';
        //     query += '(Regional_Availability__c = \'Include\' AND TE_Regions__c INCLUDES (\'' + region + '\')) OR ';
        // }
        // query = query.removeEnd(' OR ');
        // query += ') AND ';

        query = query.removeEnd(' AND ');

        return query;
    }

    public static List<Product2> getProducts(Set<Id> productIds, Boolean allowList){
        //TODO Add flag to include all internal properties of products/service types/photo sets
        //TODO for use in internal mapping (non-customer facing or cached)
        List<Product2> products = [ SELECT  Id
                                    FROM Product2
                                    WHERE Id IN :productIds];

        if(products.isEmpty()){
            throw new API_Dispatcher.APIException(404, 'Products not found');
        }

        if(allowList == false && products.size() > 1){
            throw new API_Dispatcher.APIException(300, 'Multiple products found');
        }

        return products;
    }

    public static void initProductModelMap(Set<Id> productIds, String accountId){
        OrderFunnel_ProductUtilityHelper.buildProductModelMap(productIds, accountId);
    }

    public static OrderFunnel_Models.Product2Model buildModel(String productId, String accountId){
        OrderFunnel_ProductUtilityHelper.buildProductModelMap(new Set<Id>{productId}, accountId);
        return OrderFunnel_ProductUtilityHelper.getProductModel(productId, accountId);
    }

    public static OrderFunnel_Models.ProductSearchResultModel buildSearchModel(Product2 product){
        OrderFunnel_Models.ProductSearchResultModel model = new OrderFunnel_Models.ProductSearchResultModel();
        model.Id = product.Id;
        model.externalId = product.External_ID__c;
        model.ProductName = product.Name;
        model.ProductCode = product.ProductCode;
        model.DisplayName = product.Display_Name__c;
        model.productPhotoURL = product.Product_Photo_URL__c;
        model.Type = product.RecordType.Name;
        model.Description = product.Description;
        model.Family = product.Family;
        model.MerchandisingTags = product.Merchandising_Tags__c;
        if(product.Client__c != null){
            model.clientProduct = true;
        }

        for(Component_Service__c componentService : product.Component_Services__r){
            model.ServiceTypes.add(buildServiceTypeModel(componentService));
        }
        return model;
    }

    public static OrderFunnel_Models.ServiceTypeModel buildServiceTypeModel(Component_Service__c componentService){
        OrderFunnel_Models.ServiceTypeModel model = new OrderFunnel_Models.ServiceTypeModel();
        model.Name = componentService.Service_Type__r.Name;
        model.description.customer = componentService.Service_Type__r.Customer_Description__c;
        model.description.contractor = componentService.Service_Type__r.Contractor_Description__c;
        return model;
    }

    public static CPQ_Models.ProductModel buildCPQModel(String productId, String pricebookId){
        try{
            ProductReaderContext ctx = new ProductReaderContext(pricebookId, null);
            String productJSON = SBQQ.ServiceRouter.load('SBQQ.ProductAPI.ProductLoader', productId, JSON.serialize(ctx));
            return (CPQ_Models.ProductModel) JSON.deserialize(productJSON, CPQ_Models.ProductModel.class);
        }catch(Exception ex){
            throw new API_Dispatcher.APIException(404, 'Unable to read product. ' + ex.getMessage());
        }
    }

    public class ProductReaderContext {
        public Id pricebookId;
        public String currencyCode;

        public ProductReaderContext(Id pricebookId, String currencyCode) {
            this.pricebookId = pricebookId;
            this.currencyCode = currencyCode;
        }
    }
}