force-app/main/default/objects/Account/fields/Additional_Field_Label_10__c.field-meta.xml
<CustomField>
    <fullName>Additional_Field_Label_10__c</fullName>
    <label>Additional Field Label 10</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Additional_Field_Label_11__c.field-meta.xml
<CustomField>
    <fullName>Additional_Field_Label_11__c</fullName>
    <label>Additional Field Label 11</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Additional_Field_Label_12__c.field-meta.xml
<CustomField>
    <fullName>Additional_Field_Label_12__c</fullName>
    <label>Additional Field Label 12</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Additional_Field_Label_13__c.field-meta.xml
<CustomField>
    <fullName>Additional_Field_Label_13__c</fullName>
    <label>Additional Field Label 13</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Additional_Field_Label_14__c.field-meta.xml
<CustomField>
    <fullName>Additional_Field_Label_14__c</fullName>
    <label>Additional Field Label 14</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Additional_Field_Label_15__c.field-meta.xml
<CustomField>
    <fullName>Additional_Field_Label_15__c</fullName>
    <label>Additional Field Label 15</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Additional_Field_Label_16__c.field-meta.xml
<CustomField>
    <fullName>Additional_Field_Label_16__c</fullName>
    <label>Additional Field Label 16</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Additional_Field_Label_17__c.field-meta.xml
<CustomField>
    <fullName>Additional_Field_Label_17__c</fullName>
    <label>Additional Field Label 17</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Additional_Field_Label_18__c.field-meta.xml
<CustomField>
    <fullName>Additional_Field_Label_18__c</fullName>
    <label>Additional Field Label 18</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Additional_Field_Label_19__c.field-meta.xml
<CustomField>
    <fullName>Additional_Field_Label_19__c</fullName>
    <label>Additional Field Label 19</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Additional_Field_Label_1__c.field-meta.xml
<CustomField>
    <fullName>Additional_Field_Label_1__c</fullName>
    <label>Additional Field Label 1</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Additional_Field_Label_20__c.field-meta.xml
<CustomField>
    <fullName>Additional_Field_Label_20__c</fullName>
    <label>Additional Field Label 20</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Additional_Field_Label_2__c.field-meta.xml
<CustomField>
    <fullName>Additional_Field_Label_2__c</fullName>
    <label>Additional Field Label 2</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Additional_Field_Label_3__c.field-meta.xml
<CustomField>
    <fullName>Additional_Field_Label_3__c</fullName>
    <label>Additional Field Label 3</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Additional_Field_Label_4__c.field-meta.xml
<CustomField>
    <fullName>Additional_Field_Label_4__c</fullName>
    <label>Additional Field Label 4</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Additional_Field_Label_5__c.field-meta.xml
<CustomField>
    <fullName>Additional_Field_Label_5__c</fullName>
    <label>Additional Field Label 5</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Additional_Field_Label_6__c.field-meta.xml
<CustomField>
    <fullName>Additional_Field_Label_6__c</fullName>
    <label>Additional Field Label 6</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Additional_Field_Label_7__c.field-meta.xml
<CustomField>
    <fullName>Additional_Field_Label_7__c</fullName>
    <label>Additional Field Label 7</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Additional_Field_Label_8__c.field-meta.xml
<CustomField>
    <fullName>Additional_Field_Label_8__c</fullName>
    <label>Additional Field Label 8</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Additional_Field_Label_9__c.field-meta.xml
<CustomField>
    <fullName>Additional_Field_Label_9__c</fullName>
    <label>Additional Field Label 9</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Additional_Field_Value_10__c.field-meta.xml
<CustomField>
    <fullName>Additional_Field_Value_10__c</fullName>
    <label>Additional Field Value 10</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Additional_Field_Value_11__c.field-meta.xml
<CustomField>
    <fullName>Additional_Field_Value_11__c</fullName>
    <label>Additional Field Value 11</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Additional_Field_Value_12__c.field-meta.xml
<CustomField>
    <fullName>Additional_Field_Value_12__c</fullName>
    <label>Additional Field Value 12</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Additional_Field_Value_13__c.field-meta.xml
<CustomField>
    <fullName>Additional_Field_Value_13__c</fullName>
    <label>Additional Field Value 13</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Additional_Field_Value_14__c.field-meta.xml
<CustomField>
    <fullName>Additional_Field_Value_14__c</fullName>
    <label>Additional Field Value 14</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Additional_Field_Value_15__c.field-meta.xml
<CustomField>
    <fullName>Additional_Field_Value_15__c</fullName>
    <label>Additional Field Value 15</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Additional_Field_Value_16__c.field-meta.xml
<CustomField>
    <fullName>Additional_Field_Value_16__c</fullName>
    <label>Additional Field Value 16</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Additional_Field_Value_17__c.field-meta.xml
<CustomField>
    <fullName>Additional_Field_Value_17__c</fullName>
    <label>Additional Field Value 17</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Additional_Field_Value_18__c.field-meta.xml
<CustomField>
    <fullName>Additional_Field_Value_18__c</fullName>
    <label>Additional Field Value 18</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Additional_Field_Value_19__c.field-meta.xml
<CustomField>
    <fullName>Additional_Field_Value_19__c</fullName>
    <label>Additional Field Value 19</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Additional_Field_Value_1__c.field-meta.xml
<CustomField>
    <fullName>Additional_Field_Value_1__c</fullName>
    <label>Additional Field Value 1</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Additional_Field_Value_20__c.field-meta.xml
<CustomField>
    <fullName>Additional_Field_Value_20__c</fullName>
    <label>Additional Field Value 20</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Additional_Field_Value_2__c.field-meta.xml
<CustomField>
    <fullName>Additional_Field_Value_2__c</fullName>
    <label>Additional Field Value 2</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Additional_Field_Value_3__c.field-meta.xml
<CustomField>
    <fullName>Additional_Field_Value_3__c</fullName>
    <label>Additional Field Value 3</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Additional_Field_Value_4__c.field-meta.xml
<CustomField>
    <fullName>Additional_Field_Value_4__c</fullName>
    <label>Additional Field Value 4</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Additional_Field_Value_5__c.field-meta.xml
<CustomField>
    <fullName>Additional_Field_Value_5__c</fullName>
    <label>Additional Field Value 5</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Additional_Field_Value_6__c.field-meta.xml
<CustomField>
    <fullName>Additional_Field_Value_6__c</fullName>
    <label>Additional Field Value 6</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Additional_Field_Value_7__c.field-meta.xml
<CustomField>
    <fullName>Additional_Field_Value_7__c</fullName>
    <label>Additional Field Value 7</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Additional_Field_Value_8__c.field-meta.xml
<CustomField>
    <fullName>Additional_Field_Value_8__c</fullName>
    <label>Additional Field Value 8</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Additional_Field_Value_9__c.field-meta.xml
<CustomField>
    <fullName>Additional_Field_Value_9__c</fullName>
    <label>Additional Field Value 9</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/External_ID__c.field-meta.xml
<CustomField>
    <fullName>External_ID__c</fullName>
    <externalId>true</externalId>
    <label>TE External ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/PaymentMethod__c.field-meta.xml
<CustomField>
    <fullName>PaymentMethod__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>Invoice</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/PaymentTerms__c.field-meta.xml
<CustomField>
    <fullName>PaymentTerms__c</fullName>
    <label>Payment Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Per Service</fullName>
            </value>
            <value>
                <fullName>Net 30</fullName>
            </value>
            <value>
                <fullName>Net 60</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OrderFunnel_AccountUtility.cls
public with sharing class OrderFunnel_AccountUtility {
    public static List<Account> getAccounts(String id){
        List<Account> accs = [  SELECT  Id, Name, Phone, BillingStreet, BillingCity, External_ID__c,
                                        BillingState, BillingPostalCode, BillingCountry, PaymentMethod__c, PaymentTerms__c,

                                        Additional_Field_Label_1__c, Additional_Field_Value_1__c, Additional_Field_Label_2__c, Additional_Field_Value_2__c,
                                        Additional_Field_Label_3__c, Additional_Field_Value_3__c, Additional_Field_Label_4__c, Additional_Field_Value_4__c,
                                        Additional_Field_Label_5__c, Additional_Field_Value_5__c, Additional_Field_Label_6__c, Additional_Field_Value_6__c,
                                        Additional_Field_Label_7__c, Additional_Field_Value_7__c, Additional_Field_Label_8__c, Additional_Field_Value_8__c,
                                        Additional_Field_Label_9__c, Additional_Field_Value_9__c, Additional_Field_Label_10__c, Additional_Field_Value_10__c,
                                        Additional_Field_Label_11__c, Additional_Field_Value_11__c, Additional_Field_Label_12__c, Additional_Field_Value_12__c,
                                        Additional_Field_Label_13__c, Additional_Field_Value_13__c, Additional_Field_Label_14__c, Additional_Field_Value_14__c,
                                        Additional_Field_Label_15__c, Additional_Field_Value_15__c, Additional_Field_Label_16__c, Additional_Field_Value_16__c,
                                        Additional_Field_Label_17__c, Additional_Field_Value_17__c, Additional_Field_Label_18__c, Additional_Field_Value_18__c,
                                        Additional_Field_Label_19__c, Additional_Field_Value_19__c, Additional_Field_Label_20__c, Additional_Field_Value_20__c

                                FROM    Account
                                WHERE   Id =: id];

        return accs;
    }

    public static OrderFunnel_Models.AccountModel buildModel(Account a){
        OrderFunnel_Models.AccountModel model = new OrderFunnel_Models.AccountModel();
        model.Id = a.Id;
        model.Name = a.Name;
        model.Phone = a.Phone;
        model.BillingAddress = new OrderFunnel_Models.AddressModel();
        model.BillingAddress.Street = a.BillingStreet;
        model.BillingAddress.City = a.BillingCity;
        model.BillingAddress.State = a.BillingState;
        model.BillingAddress.PostalCode = a.BillingPostalCode;
        model.BillingAddress.Country = a.BillingCountry;
        model.PaymentMethod = a.PaymentMethod__c;
        model.PaymentTerms = a.PaymentTerms__c;
        model.externalId = a.External_ID__c; // Added by Fran 05-19-2023
        model.additionalFields = OrderFunnel_Utility.buildAdditionalFieldModels(a, 'Customer');

        return model;
    }

    public static Account buildAccount(OrderFunnel_Models.AccountModel model, Account a){
        if(a == null){
            a = new Account();
            a.Id = model.Id;
        }
        a.Name = model.Name;
        a.Phone = model.Phone;
        a.BillingStreet = model.BillingAddress.Street;
        a.BillingCity = model.BillingAddress.City;
        a.BillingState = model.BillingAddress.State;
        a.BillingPostalCode = model.BillingAddress.PostalCode;
        a.BillingCountry = model.BillingAddress.Country;

        OrderFunnel_Utility.parseAdditionalFieldsModel(a, model.additionalFields, 'Customer');

        return a;
    }
}