force-app/main/default/objects/Account/fields/Additional_Field_Label_10__c.field-meta.xml
<CustomField>
    <fullName>Additional_Field_Label_10__c</fullName>
    <label>Additional Field Label 10</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Additional_Field_Label_11__c.field-meta.xml
<CustomField>
    <fullName>Additional_Field_Label_11__c</fullName>
    <label>Additional Field Label 11</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Additional_Field_Label_1__c.field-meta.xml
<CustomField>
    <fullName>Additional_Field_Label_1__c</fullName>
    <label>Additional Field Label 1</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Additional_Field_Label_2__c.field-meta.xml
<CustomField>
    <fullName>Additional_Field_Label_2__c</fullName>
    <label>Additional Field Label 2</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Additional_Field_Label_3__c.field-meta.xml
<CustomField>
    <fullName>Additional_Field_Label_3__c</fullName>
    <label>Additional Field Label 3</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Additional_Field_Label_4__c.field-meta.xml
<CustomField>
    <fullName>Additional_Field_Label_4__c</fullName>
    <label>Additional Field Label 4</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Additional_Field_Label_5__c.field-meta.xml
<CustomField>
    <fullName>Additional_Field_Label_5__c</fullName>
    <label>Additional Field Label 5</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Additional_Field_Label_6__c.field-meta.xml
<CustomField>
    <fullName>Additional_Field_Label_6__c</fullName>
    <label>Additional Field Label 6</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Additional_Field_Label_7__c.field-meta.xml
<CustomField>
    <fullName>Additional_Field_Label_7__c</fullName>
    <label>Additional Field Label 7</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Additional_Field_Label_8__c.field-meta.xml
<CustomField>
    <fullName>Additional_Field_Label_8__c</fullName>
    <label>Additional Field Label 8</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Additional_Field_Label_9__c.field-meta.xml
<CustomField>
    <fullName>Additional_Field_Label_9__c</fullName>
    <label>Additional Field Label 9</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Additional_Field_Value_10__c.field-meta.xml
<CustomField>
    <fullName>Additional_Field_Value_10__c</fullName>
    <label>Additional Field Value 10</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Additional_Field_Value_11__c.field-meta.xml
<CustomField>
    <fullName>Additional_Field_Value_11__c</fullName>
    <label>Additional Field Value 11</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Additional_Field_Value_1__c.field-meta.xml
<CustomField>
    <fullName>Additional_Field_Value_1__c</fullName>
    <label>Additional Field Value 1</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Additional_Field_Value_2__c.field-meta.xml
<CustomField>
    <fullName>Additional_Field_Value_2__c</fullName>
    <label>Additional Field Value 2</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Additional_Field_Value_3__c.field-meta.xml
<CustomField>
    <fullName>Additional_Field_Value_3__c</fullName>
    <label>Additional Field Value 3</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Additional_Field_Value_4__c.field-meta.xml
<CustomField>
    <fullName>Additional_Field_Value_4__c</fullName>
    <label>Additional Field Value 4</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Additional_Field_Value_5__c.field-meta.xml
<CustomField>
    <fullName>Additional_Field_Value_5__c</fullName>
    <label>Additional Field Value 5</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Additional_Field_Value_6__c.field-meta.xml
<CustomField>
    <fullName>Additional_Field_Value_6__c</fullName>
    <label>Additional Field Value 6</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Additional_Field_Value_7__c.field-meta.xml
<CustomField>
    <fullName>Additional_Field_Value_7__c</fullName>
    <label>Additional Field Value 7</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Additional_Field_Value_8__c.field-meta.xml
<CustomField>
    <fullName>Additional_Field_Value_8__c</fullName>
    <label>Additional Field Value 8</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Additional_Field_Value_9__c.field-meta.xml
<CustomField>
    <fullName>Additional_Field_Value_9__c</fullName>
    <label>Additional Field Value 9</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used to set a default Price Book for an Account. This Price Book will be inherited by the Opportunity / Quote generated from this Account.</description>
    <inlineHelpText>Used to set a default Price Book for an Account. This Price Book will be inherited by the Opportunity / Quote generated from this Account.</inlineHelpText>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Access_Code__c.field-meta.xml
<CustomField>
    <fullName>Access_Code__c</fullName>
    <label>Access Code</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Access_Note__c.field-meta.xml
<CustomField>
    <fullName>Access_Note__c</fullName>
    <description>Note related to property access.</description>
    <label>Access Note</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Additional_Field_Label_4__c.field-meta.xml
<CustomField>
    <fullName>Additional_Field_Label_4__c</fullName>
    <label>Additional Field Label 4</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Additional_Field_Label_6__c.field-meta.xml
<CustomField>
    <fullName>Additional_Field_Label_6__c</fullName>
    <label>Additional Field Label 6</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Additional_Field_Label_7__c.field-meta.xml
<CustomField>
    <fullName>Additional_Field_Label_7__c</fullName>
    <label>Additional Field Label 7</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Additional_Field_Label_8__c.field-meta.xml
<CustomField>
    <fullName>Additional_Field_Label_8__c</fullName>
    <label>Additional Field Label 8</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Additional_Field_Value_11__c.field-meta.xml
<CustomField>
    <fullName>Additional_Field_Value_11__c</fullName>
    <label>Additional Field Value 11</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Additional_Field_Value_4__c.field-meta.xml
<CustomField>
    <fullName>Additional_Field_Value_4__c</fullName>
    <label>Additional Field Value 4</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Additional_Field_Value_5__c.field-meta.xml
<CustomField>
    <fullName>Additional_Field_Value_5__c</fullName>
    <label>Additional Field Value 5</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Additional_Field_Value_8__c.field-meta.xml
<CustomField>
    <fullName>Additional_Field_Value_8__c</fullName>
    <label>Additional Field Value 8</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/CU_Property_Id__c.field-meta.xml
<CustomField>
    <fullName>CU_Property_Id__c</fullName>
    <label>Customer Property Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Current_Tracing_ID__c.field-meta.xml
<CustomField>
    <fullName>Current_Tracing_ID__c</fullName>
    <label>Current Tracing ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Postal_Code__c</fullName>
    <label>Postal Code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Region</label>
    <referenceTo>Region__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Street_Address__c.field-meta.xml
<CustomField>
    <fullName>Street_Address__c</fullName>
    <label>Street Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/TE_Property_Id__c.field-meta.xml
<CustomField>
    <fullName>TE_Property_Id__c</fullName>
    <externalId>true</externalId>
    <label>TE Property Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property_Metric_Map__mdt/Property_Metric_Map__mdt.object-meta.xml
<CustomObject>
    <label>Property Metric Map</label>
    <pluralLabel>Property Metric Maps</pluralLabel>
</CustomObject>

force-app/main/default/objects/Property_Metric_Map__mdt/fields/Asset_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Asset_Field_API_Name__c</fullName>
    <label>Asset Field API Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property_Tracing__c/Property_Tracing__c.object-meta.xml
<CustomObject>
    <label>Property Tracing Request</label>
    <nameField>
        <displayFormat>PT-{0000000000}</displayFormat>
        <label>Property Tracing Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Property Tracing Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Property_Tracing__c/fields/TE_Property_Id__c.field-meta.xml
<CustomField>
    <fullName>TE_Property_Id__c</fullName>
    <externalId>true</externalId>
    <label>TE Property Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Region__c/Region__c.object-meta.xml
<CustomObject>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Region__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>Primary city of the zip code</description>
    <label>Primary City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Region__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Regions</relationshipLabel>
    <relationshipName>Regions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Region__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>SD</fullName>
            </value>
            <value>
                <fullName>NJ</fullName>
            </value>
            <value>
                <fullName>PA</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OrderFunnel_AssetUtility.cls
public with sharing class OrderFunnel_AssetUtility {

    private static Map<String, String> assetMetrics;
    public static Map<String, String> getAssetMetrics(){
        if(assetMetrics == null){
            Map<String, SObjectField> assetFields = getAssetFields();
            assetMetrics = new Map<String, String>();

            for(Property_Metric_Map__mdt metric : [ SELECT  MasterLabel, Asset_Field_API_Name__c
                                                    FROM    Property_Metric_Map__mdt ]){
                if (assetFields.containsKey(metric.Asset_Field_API_Name__c)) {
                    assetMetrics.put(metric.Asset_Field_API_Name__c, metric.MasterLabel);
                    assetMetrics.put(metric.MasterLabel, metric.Asset_Field_API_Name__c);
                }
            }
        }

        return assetMetrics;
    }

    @testVisible
    private static Map<String, SObjectField> getAssetFields(){
        return Asset.sObjectType.getDescribe().fields.getMap();
    }

    public static List<Asset> getAssets(String accountId, String propertyId, String assetId, Boolean allowList){
        String query = buildQuery(accountId, propertyId, assetId);

        List<Asset> assets = (List<Asset>) Database.query(query);

        if(assets.isEmpty()){
            throw new API_Dispatcher.APIException(404, 'Asset not found');
        }

        if(allowList == false && assets.size() > 1){
            throw new API_Dispatcher.APIException(300, 'Multiple assets identified');
        }

        return assets;
    }

    @testVisible
    private static String buildQuery(String accountId, String propertyId, String assetId){
        String query = 'SELECT Id, Name, AccountId, Account.Price_Book__c, TE_Property_Id__c, CU_Property_Id__c, Current_Tracing_ID__c, ';
        query += 'Street_Address__c, City__c, State__c, Postal_Code__c, Property_Location__Latitude__s, Property_Location__Longitude__s, ';
        query += 'Access_Code__c, Access_Note__c, Region__c, Region__r.Name, Region__r.TE_Region__c, Region__r.Price_Book__c, ';
        query += getAssetMetricFieldsString('');
        query += 'Additional_Field_Label_1__c, Additional_Field_Value_1__c, Additional_Field_Label_2__c, Additional_Field_Value_2__c, ';
        query += 'Additional_Field_Label_3__c, Additional_Field_Value_3__c, Additional_Field_Label_4__c, Additional_Field_Value_4__c, ';
        query += 'Additional_Field_Label_5__c, Additional_Field_Value_5__c, Additional_Field_Label_6__c, Additional_Field_Value_6__c, ';
        query += 'Additional_Field_Label_7__c, Additional_Field_Value_7__c, Additional_Field_Label_8__c, Additional_Field_Value_8__c, ';
        query += 'Additional_Field_Label_9__c, Additional_Field_Value_9__c, Additional_Field_Label_10__c, Additional_Field_Value_10__c, ';
        query += 'Additional_Field_Label_11__c, Additional_Field_Value_11__c, Additional_Field_Label_12__c, Additional_Field_Value_12__c, ';
        query += 'Additional_Field_Label_13__c, Additional_Field_Value_13__c, Additional_Field_Label_14__c, Additional_Field_Value_14__c, ';
        query += 'Additional_Field_Label_15__c, Additional_Field_Value_15__c, Additional_Field_Label_16__c, Additional_Field_Value_16__c, ';
        query += 'Additional_Field_Label_17__c, Additional_Field_Value_17__c, Additional_Field_Label_18__c, Additional_Field_Value_18__c, ';
        query += 'Additional_Field_Label_19__c, Additional_Field_Value_19__c, Additional_Field_Label_20__c, Additional_Field_Value_20__c ';

        query += 'FROM Asset ';

        query += 'WHERE ';
        if(accountId != null && accountId != ''){
            query += 'AccountId = :accountId AND ';
        }
        if(propertyId != null && propertyId != ''){
            query += 'TE_Property_Id__c = :propertyId AND ';
        }
        if(assetId != null && assetId != ''){
            query += 'Id = :assetId';
        }

        query = query.removeEnd(' AND ');

        return query;
    }

    public static String getAssetMetricFieldsString(String prefix){
        if(prefix == null){
            prefix = '';
        }

        String fieldsString = '';
        for(String metric : getAssetMetrics().keySet()){
            if(metric.endsWith('__c')){
                fieldsString += prefix + metric + ', ';
            }
        }
        return fieldsString;
    }

    public static OrderFunnel_Models.AssetModel buildModel(Asset a){
        OrderFunnel_Models.AssetModel model = new OrderFunnel_Models.AssetModel();
        model.Name = a.Name;
        model.AccountId = a.AccountId;
        model.SFID = a.Id;
        model.TEID = a.TE_Property_Id__c;
        model.CUID = a.CU_Property_Id__c;
        model.CurrentTracingId = a.Current_Tracing_ID__c;
        model.Address = new OrderFunnel_Models.AddressModel();
        model.Address.Street = a.Street_Address__c;
        model.Address.City = a.City__c;
        model.Address.State = a.State__c;
        model.Address.PostalCode = a.Postal_Code__c;
        model.Address.latitude = a.Property_Location__Latitude__s;
        model.Address.longitude = a.Property_Location__Longitude__s;
        model.teRegionId = a.Region__c;
        model.teRegionName = a.Region__r.Name;
        model.pricebookId = a.Region__r.Price_book__c;
        model.accessCode = a.Access_Code__c;
        model.accessNote = a.Access_Note__c;

        model.additionalFields = OrderFunnel_Utility.buildAdditionalFieldModels(a, 'Asset');

        for (String metricFieldName : getAssetMetrics().keySet()) {
            if(metricFieldName.endsWith('__c') && a.get(metricFieldName) != null) {
                OrderFunnel_Models.MetricModel metric = new OrderFunnel_Models.MetricModel();
                metric.Type = getAssetMetrics().get(metricFieldName);
                metric.Value = ((Decimal) a.get(metricFieldName)).toPlainString();
                model.Metrics.add(metric);
            }
        }
        return model;
    }

    public static Asset buildAsset(OrderFunnel_Models.AssetModel model, Asset a){
        if(a == null){
            a = new Asset();
            a.Id = model.sfId;
        }
        a.Name = model.Name;
        a.AccountId = model.AccountId;
        a.TE_Property_Id__c = model.TEID;
        a.CU_Property_Id__c = model.CUID;
        a.Current_Tracing_ID__c = model.CurrentTracingId;
        a.Status = model.status;

        if (model.Address != null) {
            a.Street_Address__c = model.Address.Street;
            a.City__c = model.Address.City;
            a.State__c = model.Address.State;
            a.Postal_Code__c = model.Address.PostalCode;
            a.Property_Location__Latitude__s = model.Address.latitude;
            a.Property_Location__Longitude__s = model.Address.longitude;
        }

        a.Access_Code__c = model.accessCode;
        a.Access_Note__c = model.accessNote;


        OrderFunnel_Utility.parseAdditionalFieldsModel(a, model.additionalFields, 'Asset');

        if(model.Metrics != null){
            //Note that nullifying metric fields requires a specific nil. The absence of a submission
            //will not cause the values to be erased.

            for (OrderFunnel_Models.MetricModel m : model.Metrics) {
                if (getAssetMetrics().containsKey(m.Type) == false) {
                    throw new API_Dispatcher.APIException(400, 'Metric field not mapped for: ' + m.Type);
                }

                a.put(getAssetMetrics().get(m.Type), Decimal.valueOf(m.Value));
            }
        }
        return a;
    }

    public static Property_Tracing__c requestRetrace(String assetId, List<OrderFunnel_Models.MetricModel> metrics) {
        Property_Tracing__c pt = new Property_Tracing__c();
        pt.Asset__c = assetId;
        String metricsChoices = '';
        for (OrderFunnel_Models.MetricModel m : metrics) {
            metricsChoices += m.Type + ';';
        }
        metricsChoices = metricsChoices.removeEnd(';');
        pt.Metrics__c = metricsChoices;

        return pt;

    }
}