force-app/main/default/objects/Account/fields/Domain__c.field-meta.xml
<CustomField>
    <fullName>Domain__c</fullName>
    <description>The email domain to be used for clients needing domain-based routing.  This should only be filled in for clients on Client Teams 1-3.</description>
    <inlineHelpText>Email domain for domain-based routing to Client Teams 1-3.  Do not fill in if the client ops is not managed by one of those three teams.</inlineHelpText>
    <label>Email Domain</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Is_this_a_registered_company__c.field-meta.xml
<CustomField>
    <fullName>Is_this_a_registered_company__c</fullName>
    <label>Is this a registered company?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Domain__c.field-meta.xml
<CustomField>
    <fullName>Domain__c</fullName>
    <label>Domain</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EB_CaseTriggerTest.cls
@isTest 
public class EB_CaseTriggerTest {
    
    @isTest
    private static void caseWithRelatedAccountDomain() {
        Account acc = new Account();
        acc.Domain__c = 'test.com';
        acc.Is_this_a_registered_company__c = 'Yes';
        acc.Name = 'KelseyTest';
        insert acc;

        Id [] fixedSearchResults= new Id[1];
        fixedSearchResults[0] = acc.Id;
        Test.setFixedSearchResults(fixedSearchResults);
        
        Case c = new Case();
        c.SuppliedEmail = 'test@test.com';

        Test.startTest();
        insert c;
        Test.stopTest();

        Case TriggerResult = [SELECT AccountId, Domain__c FROM Case WHERE Id =: c.Id];

        System.assertEquals(acc.Id, TriggerResult.AccountId);
        System.assertEquals(acc.Domain__c, TriggerResult.Domain__c);

        
    }

    @isTest
    private static void caseWithNoRelatedAccountDomain() {
        Account acc = new Account();
        acc.Is_this_a_registered_company__c = 'Yes';
        acc.Name = 'KelseyTest';
        insert acc;

        Id [] fixedSearchResults= new Id[1];
        fixedSearchResults[0] = null;
        Test.setFixedSearchResults(fixedSearchResults);
        
        Case c = new Case();
        c.SuppliedEmail = 'test@test.com';

        Test.startTest();
        insert c;
        Test.stopTest();

        Case TriggerResult = [SELECT AccountId, Domain__c FROM Case WHERE Id =: c.Id];
        
        System.assertEquals(null, TriggerResult.AccountId);
        System.assertEquals('test.com', TriggerResult.Domain__c);

    }

    @isTest
    private static void caseWithNoSuppliedEmailDomain() {
        Account acc = new Account();
        acc.Domain__c = 'test.com';
        acc.Is_this_a_registered_company__c = 'Yes';
        acc.Name = 'KelseyTest';
        insert acc;

        Id [] fixedSearchResults= new Id[1];
        fixedSearchResults[0] = null;
        Test.setFixedSearchResults(fixedSearchResults);
        
        Case c = new Case();

        Test.startTest();
        insert c;
        Test.stopTest();

        Case TriggerResult = [SELECT AccountId, Domain__c FROM Case WHERE Id =: c.Id];
        
        System.assertEquals(null, TriggerResult.AccountId);
        System.assertEquals(null, TriggerResult.Domain__c);
    }

    
}