force-app/main/default/objects/Account/fields/External_ID__c.field-meta.xml
<CustomField>
    <fullName>External_ID__c</fullName>
    <externalId>true</externalId>
    <label>TE External ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Component_Service__c/Component_Service__c.object-meta.xml
<CustomObject>
    <label>Component Service</label>
    <nameField>
        <displayFormat>CS-{00000}</displayFormat>
        <label>Component Service Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Component Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Component_Service__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Component Services</relationshipLabel>
    <relationshipName>Component_Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Component_Service__c/fields/Service_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Type</label>
    <referenceTo>Service_Type__c</referenceTo>
    <relationshipLabel>Component Services</relationshipLabel>
    <relationshipName>Component_Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Component_Service__c/fields/Service_Type_Description__c.field-meta.xml
<CustomField>
    <fullName>Service_Type_Description__c</fullName>
    <description>Customer facing service type description.</description>
    <label>Service Type Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Photo__c/Photo__c.object-meta.xml
<CustomObject>
    <label>Photo</label>
    <nameField>
        <label>Photo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Photos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Photo__c/fields/Before_Service__c.field-meta.xml
<CustomField>
    <fullName>Before_Service__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Before Service</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Photo_Set_Item__c/Photo_Set_Item__c.object-meta.xml
<CustomObject>
    <label>Photo Set Item</label>
    <nameField>
        <displayFormat>PSI-{00000}</displayFormat>
        <label>Photo Set Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Photo Set Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Photo_Set_Item__c/fields/Photo__c.field-meta.xml
<CustomField>
    <fullName>Photo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Photo</label>
    <referenceTo>Photo__c</referenceTo>
    <relationshipLabel>Photo Set Items</relationshipLabel>
    <relationshipName>Photo_Set_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Photo_Set_Item__c/fields/Service_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Type</label>
    <referenceTo>Service_Type__c</referenceTo>
    <relationshipLabel>Photo Set Items</relationshipLabel>
    <relationshipName>Photo_Set_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Merchandising_Tags__c.field-meta.xml
<CustomField>
    <fullName>Merchandising_Tags__c</fullName>
    <label>Product Categories</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Most Popular</fullName>
            </value>
            <value>
                <fullName>Best Value</fullName>
            </value>
            <value>
                <fullName>Garden Beds</fullName>
            </value>
            <value>
                <fullName>Seasonal Cleanup</fullName>
            </value>
            <value>
                <fullName>Trees &amp; Bushes</fullName>
            </value>
            <value>
                <fullName>Landscaping</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/Component.recordType-meta.xml
<RecordType>
    <fullName>Component</fullName>
    <active>true</active>
    <label>Component</label>
</RecordType>

force-app/main/default/objects/Service_Type__c/Service_Type__c.object-meta.xml
<CustomObject>
    <label>Service Type</label>
    <nameField>
        <label>Service Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Type__c/fields/Contractor_Description__c.field-meta.xml
<CustomField>
    <fullName>Contractor_Description__c</fullName>
    <label>Contractor Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/classes/OrderFunnel_ProductHandlerTest.cls
@isTest
public with sharing class OrderFunnel_ProductHandlerTest {
    @isTest
    public static void handleGet_Success(){
        Product2 prod = new Product2();
        prod.Name = 'Test Product';
        prod.Display_Name__c = 'Test Product';
        prod.ProductCode = 'TESTPROD';
        prod.IsActive = true;
        prod.Merchandising_Tags__c = 'Most Popular;Best Value';
        insert prod;

        Service_Type__c service = new Service_Type__c(Contractor_Description__c = 'Description', Name = 'Name', External_ID__c = prod.id);
        insert service;
        
        Component_Service__c component = new Component_Service__c(Product__c = prod.Id, Service_Type__c = service.id, Service_Type_Description__c = 'Des');
		insert component;
        
        Photo__c photo = new Photo__c(Before_Service__c = true, Name = 'Name');
        insert photo;
        
        Photo_Set_Item__c photoSet = new Photo_Set_Item__c(Service_Type__c = service.id, Photo__c = photo.id);
        insert photoSet;
        
        RestRequest req = new RestRequest();
        req.requestURI = '/orderfunnel/product/' + prod.Id;

        OrderFunnel_ProductHandler handler = new OrderFunnel_ProductHandler();

        Test.startTest();

        List<OrderFunnel_Models.Product2Model> models = (List<OrderFunnel_Models.Product2Model>) handler.handleGet(req);

        Test.stopTest();

        System.assertEquals(1, models.size());
    }

    @isTest
    public static void handleGet_InvalidAccount(){

        RestRequest req = new RestRequest();
        req.requestURI = '/orderfunnel/product/01t000000000000';
        req.params.put('accountId', '003000000000000');

        OrderFunnel_ProductHandler handler = new OrderFunnel_ProductHandler();

        Test.startTest();

        try{
            handler.handleGet(req);
            System.assert(false, 'Exception expected: Invalid account id');
        }catch(API_Dispatcher.APIException ex){
            System.assertEquals(400, ex.statusCode);
            System.assert(ex.getMessage().contains('Account identifier invalid'));
        }catch(Exception ex){
            System.assert(false, 'APIException expected: ' + ex.getTypeName() + ' presented');
        }

        Test.stopTest();
    }

    @isTest
    public static void handleGet_InvalidProduct(){
        RestRequest req = new RestRequest();
        req.requestURI = '/orderfunnel/product/001000000000000';

        OrderFunnel_ProductHandler handler = new OrderFunnel_ProductHandler();

        Test.startTest();

        try{
            handler.handleGet(req);
            System.assert(false, 'Exception expected: Invalid product id');
        }catch(API_Dispatcher.APIException ex){
            System.assertEquals(400, ex.statusCode);
            System.assert(ex.getMessage().contains('Product identifier invalid'));
        }catch(Exception ex){
            System.assert(false, 'APIException expected: ' + ex.getTypeName() + ' presented');
        }

        Test.stopTest();
    }
}