force-app/main/default/objects/Account/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used to set a default Price Book for an Account. This Price Book will be inherited by the Opportunity / Quote generated from this Account.</description>
    <inlineHelpText>Used to set a default Price Book for an Account. This Price Book will be inherited by the Opportunity / Quote generated from this Account.</inlineHelpText>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contracted_Discount__c/Contracted_Discount__c.object-meta.xml
<CustomObject>
    <label>Contracted Discount</label>
    <nameField>
        <displayFormat>CD-{YY}-{000000}</displayFormat>
        <label>Contracted Discount Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contracted Discounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contracted_Discount__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contracted Discounts</relationshipLabel>
    <relationshipName>Contracted_Discounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contracted_Discount__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Contracted Discounts</relationshipLabel>
    <relationshipName>Contracted_Discounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contracted_Discount__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Contracted Discounts</relationshipLabel>
    <relationshipName>Contracted_Discounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OrderFunnel_PricebookTest.cls
@isTest
public class OrderFunnel_PricebookTest {
    
    @IsTest
    public static void testGET(){

        Product2 prod = new Product2();
        prod.Name = 'Test Product';
        prod.Display_Name__c = 'Test Product';
        prod.ProductCode = 'TESTPROD';
        prod.IsActive = true;
        insert prod;

        PricebookEntry pbe = new PricebookEntry();
        pbe.Pricebook2Id = Test.getStandardPricebookId();
        pbe.Product2Id = prod.Id;
        pbe.UnitPrice = 1;
        pbe.IsActive = true;
        insert pbe;

        Pricebook2 customPricebook = new Pricebook2();
        customPricebook.Name = 'Custom';
        customPricebook.IsActive = true;
        insert customPricebook;

        PricebookEntry pbc = new PricebookEntry();
        pbc.Pricebook2Id = customPricebook.Id;
        pbc.Product2Id = prod.Id;
        pbc.UnitPrice = 1;
        pbc.IsActive = true;
        insert pbc;

        Account acc = new Account();
        acc.Name = 'Test Account';
        insert acc;
    
        Contracted_Discount__c contractedDiscount = new Contracted_Discount__c();
        contractedDiscount.Account__c = acc.id;
        contractedDiscount.Price_Book__c = customPricebook.Id;
        contractedDiscount.Product__c = prod.id;
        insert contractedDiscount;

        RestRequest req = new RestRequest();
        req.requestURI = '/orderfunnel/pricebook/' + customPricebook.Id;
        RestContext.request = req;

        RestResponse resp = new RestResponse();
        RestContext.response = resp;

        Test.startTest();
            OrderFunnel_Pricebook.doGet();
        Test.stopTest();

        System.assertEquals(200, resp.statusCode);
    }

    @IsTest
    public static void doPost(){
        RestRequest req = new RestRequest();
        RestContext.request = req;

        RestResponse resp = new RestResponse();
        RestContext.response = resp;

        Test.startTest();
            OrderFunnel_Pricebook.doPost();
        Test.stopTest();

        System.assertEquals(501, resp.statusCode);
    }

    @IsTest
    public static void testPATCH(){
        RestRequest req = new RestRequest();
        req.requestURI = '/orderfunnel/pricebook/' + Test.getStandardPricebookId();
        //req.requestBody = Blob.valueOf(JSON.serialize(accModel));
        RestContext.request = req;

        RestResponse resp = new RestResponse();
        RestContext.response = resp;

        Test.startTest();
            OrderFunnel_Pricebook.doPatch();
        Test.stopTest();

        System.assertEquals(501, resp.statusCode);
    }

    @IsTest
    public static void testPUT(){
        RestRequest req = new RestRequest();
        RestContext.request = req;

        RestResponse resp = new RestResponse();
        RestContext.response = resp;

        Test.startTest();
            OrderFunnel_Pricebook.doPut();
        Test.stopTest();

        System.assertEquals(501, resp.statusCode);
    }

    @IsTest
    public static void testDELETE(){
        RestRequest req = new RestRequest();
        RestContext.request = req;

        RestResponse resp = new RestResponse();
        RestContext.response = resp;


        Test.startTest();
            OrderFunnel_Pricebook.doDelete();
        Test.stopTest();

        System.assertEquals(501, resp.statusCode);
    }
}