force-app/main/default/objects/ObjectPermission__mdt/ObjectPermission__mdt.object-meta.xml
<CustomObject>
    <label>Object Permission</label>
    <pluralLabel>Object Permissions</pluralLabel>
</CustomObject>

force-app/main/default/objects/ObjectPermission__mdt/fields/DoNotDelete__c.field-meta.xml
<CustomField>
    <fullName>DoNotDelete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Do not Delete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Tasks.cls
public class Tasks extends fflib_SObjectDomain{

    public Tasks(List<Task> sObjectList) {
        super(sObjectList);
    }
    
    public class Constructor implements fflib_SObjectDomain.IConstructable {
        public fflib_SObjectDomain construct(List<SObject> sObjectList) {
            return new Tasks(sObjectList);
        }
    }

    public override void onBeforeDelete() {
        ObjectPermission__mdt ObjectPermission = new ObjectPermissionSelector().selectByProfileAndObject('Task');

        for (Task item : (List<Task>) Records) {
            if (ObjectPermission.DoNotDelete__c) {
                item.addError(Label.TaskDeletion);
            }
        }
    }
}