force-app/main/default/objects/Object__mdt/fields/ObjectAPI__c.field-meta.xml
<CustomField>
    <fullName>ObjectAPI__c</fullName>
    <label>Object API</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ObjectPermission__mdt/ObjectPermission__mdt.object-meta.xml
<CustomObject>
    <label>Object Permission</label>
    <pluralLabel>Object Permissions</pluralLabel>
</CustomObject>

force-app/main/default/objects/ObjectPermission__mdt/fields/DoNotDelete__c.field-meta.xml
<CustomField>
    <fullName>DoNotDelete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Do not Delete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ObjectPermission__mdt/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <referenceTo>Object__mdt</referenceTo>
    <relationshipLabel>Object Permissions</relationshipLabel>
    <relationshipName>Object_Permissions</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/ObjectPermission__mdt/fields/Profile__c.field-meta.xml
<CustomField>
    <fullName>Profile__c</fullName>
    <label>Profile</label>
    <referenceTo>Profile__mdt</referenceTo>
    <relationshipLabel>Object Permissions</relationshipLabel>
    <relationshipName>Object_Permissions</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Profile__mdt/Profile__mdt.object-meta.xml
<CustomObject>
    <label>Profile</label>
    <pluralLabel>Profiles</pluralLabel>
</CustomObject>

force-app/main/default/classes/ObjectPermissionSelector.cls
public without sharing class ObjectPermissionSelector extends fflib_SObjectSelector{

    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField> {
            ObjectPermission__mdt.Id,
            ObjectPermission__mdt.Label,
            ObjectPermission__mdt.Developername,
            ObjectPermission__mdt.DoNotDelete__c,
            ObjectPermission__mdt.Object__c,
            ObjectPermission__mdt.Profile__c
        };
    }

    public Schema.SObjectType getSObjectType() {
        return ObjectPermission__mdt.sObjectType;
    }
    
    public ObjectPermission__mdt selectByProfileAndObject(String objectApiName) {
        String profileName = [SELECT Name FROM Profile WHERE Id =: UserInfo.getProfileId()].Name;
        fflib_QueryFactory newQuery = newQueryFactory();
        newQuery.setCondition('Profile__r.Label =: profileName AND Object__r.ObjectAPI__c =: objectApiName').toSOQL();

        list<ObjectPermission__mdt> resul = Database.query(newQuery.toSOQL());
        if (!resul.isEmpty()) {
            return resul[0];
        }

        return new ObjectPermission__mdt();
    }
}