force-app/main/default/objects/Component_Service__c/Component_Service__c.object-meta.xml
<CustomObject>
    <label>Component Service</label>
    <nameField>
        <displayFormat>CS-{00000}</displayFormat>
        <label>Component Service Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Component Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Component_Service__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Component Services</relationshipLabel>
    <relationshipName>Component_Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Component_Service__c/fields/Service_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Type</label>
    <referenceTo>Service_Type__c</referenceTo>
    <relationshipLabel>Component Services</relationshipLabel>
    <relationshipName>Component_Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Photo__c/Photo__c.object-meta.xml
<CustomObject>
    <label>Photo</label>
    <nameField>
        <label>Photo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Photos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Photo__c/fields/After_Service__c.field-meta.xml
<CustomField>
    <fullName>After_Service__c</fullName>
    <defaultValue>false</defaultValue>
    <label>After Service</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Photo__c/fields/Before_Service__c.field-meta.xml
<CustomField>
    <fullName>Before_Service__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Before Service</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Photo__c/fields/Instructional_Photo__c.field-meta.xml
<CustomField>
    <fullName>Instructional_Photo__c</fullName>
    <label>Instructional Photo</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Photo__c/fields/Sample_Photo__c.field-meta.xml
<CustomField>
    <fullName>Sample_Photo__c</fullName>
    <label>Sample Photo</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Photo__c/fields/Service_in_Action__c.field-meta.xml
<CustomField>
    <fullName>Service_in_Action__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Service in Action</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Photo_Set_Item__c/Photo_Set_Item__c.object-meta.xml
<CustomObject>
    <label>Photo Set Item</label>
    <nameField>
        <displayFormat>PSI-{00000}</displayFormat>
        <label>Photo Set Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Photo Set Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Photo_Set_Item__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Photo Set Items</relationshipLabel>
    <relationshipName>Photo_Set_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Photo_Set_Item__c/fields/Photo__c.field-meta.xml
<CustomField>
    <fullName>Photo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Photo</label>
    <referenceTo>Photo__c</referenceTo>
    <relationshipLabel>Photo Set Items</relationshipLabel>
    <relationshipName>Photo_Set_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Photo_Set_Item__c/fields/Service_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Type</label>
    <referenceTo>Service_Type__c</referenceTo>
    <relationshipLabel>Photo Set Items</relationshipLabel>
    <relationshipName>Photo_Set_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Estimated_Effort_Coefficient__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Effort_Coefficient__c</fullName>
    <label>Estimated Effort Coefficient</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Merchandising_Tags__c.field-meta.xml
<CustomField>
    <fullName>Merchandising_Tags__c</fullName>
    <label>Product Categories</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Most Popular</fullName>
            </value>
            <value>
                <fullName>Best Value</fullName>
            </value>
            <value>
                <fullName>Garden Beds</fullName>
            </value>
            <value>
                <fullName>Seasonal Cleanup</fullName>
            </value>
            <value>
                <fullName>Trees &amp; Bushes</fullName>
            </value>
            <value>
                <fullName>Landscaping</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Netsuite_Item__c.field-meta.xml
<CustomField>
    <fullName>Netsuite_Item__c</fullName>
    <externalId>true</externalId>
    <label>Netsuite Item</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Family__c.field-meta.xml
<CustomField>
    <fullName>Product_Family__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Family</label>
    <referenceTo>Product_Family__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Photo_URL__c.field-meta.xml
<CustomField>
    <fullName>Product_Photo_URL__c</fullName>
    <label>Product Photo URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Service_Template_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Template_Type__c</fullName>
    <label>Default Service Template Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Service_Template_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/Component.recordType-meta.xml
<RecordType>
    <fullName>Component</fullName>
    <active>true</active>
    <label>Component</label>
</RecordType>

force-app/main/default/objects/Product_Family__c/Product_Family__c.object-meta.xml
<CustomObject>
    <label>Product Family</label>
    <nameField>
        <label>Product Family Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Families</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Family__c/fields/Icon_Tag__c.field-meta.xml
<CustomField>
    <fullName>Icon_Tag__c</fullName>
    <label>Icon Tag</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Icons</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Family__c/fields/Marketing_Description__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Description__c</fullName>
    <label>Marketing Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Service_Template__c/Service_Template__c.object-meta.xml
<CustomObject>
    <label>Service Template</label>
    <nameField>
        <label>Service Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Template__c/fields/AFM_Zone__c.field-meta.xml
<CustomField>
    <fullName>AFM_Zone__c</fullName>
    <label>AFM Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>AFM_Zone</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Template__c/fields/Service_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Service_Schedule__c</fullName>
    <label>Service Schedule</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Template__c/fields/Service_Template_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Template_Type__c</fullName>
    <label>Service Template Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Service_Template_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Type__c/Service_Type__c.object-meta.xml
<CustomObject>
    <label>Service Type</label>
    <nameField>
        <label>Service Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Type__c/fields/Contractor_Description__c.field-meta.xml
<CustomField>
    <fullName>Contractor_Description__c</fullName>
    <label>Contractor Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Service_Type__c/fields/Customer_Description__c.field-meta.xml
<CustomField>
    <fullName>Customer_Description__c</fullName>
    <label>Customer Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/globalValueSets/AFM_Zone.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>A</fullName>
    </customValue>
    <customValue>
        <fullName>B</fullName>
    </customValue>
    <customValue>
        <fullName>C</fullName>
    </customValue>
    <customValue>
        <fullName>D</fullName>
    </customValue>
    <customValue>
        <fullName>E</fullName>
    </customValue>
    <customValue>
        <fullName>F</fullName>
    </customValue>
    <masterLabel>AFM Zone</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Product_Icons.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>icon_service_aeration</fullName>
    </customValue>
    <customValue>
        <fullName>icon_service_bid_removal</fullName>
    </customValue>
    <customValue>
        <fullName>icon_service_bid_request</fullName>
    </customValue>
    <customValue>
        <fullName>icon_service_bush_removal</fullName>
    </customValue>
    <customValue>
        <fullName>icon_service_bush_trimming</fullName>
    </customValue>
    <customValue>
        <fullName>icon_service_carpet_cleaning</fullName>
    </customValue>
    <customValue>
        <fullName>icon_service_carpet_installation</fullName>
    </customValue>
    <customValue>
        <fullName>icon_service_change_air_filter</fullName>
    </customValue>
    <customValue>
        <fullName>icon_service_clean_gutters</fullName>
    </customValue>
    <customValue>
        <fullName>icon_service_clean_windows</fullName>
    </customValue>
    <customValue>
        <fullName>icon_service_cleaning_service</fullName>
    </customValue>
    <customValue>
        <fullName>icon_service_custom</fullName>
    </customValue>
    <customValue>
        <fullName>icon_service_debris_removal</fullName>
    </customValue>
    <customValue>
        <fullName>icon_service_deck</fullName>
    </customValue>
    <customValue>
        <fullName>icon_service_desertscape</fullName>
    </customValue>
    <customValue>
        <fullName>icon_service_dethatching</fullName>
    </customValue>
    <customValue>
        <fullName>icon_service_edging</fullName>
    </customValue>
    <customValue>
        <fullName>icon_service_fence</fullName>
    </customValue>
    <customValue>
        <fullName>icon_service_fertilization</fullName>
    </customValue>
    <customValue>
        <fullName>icon_service_greenman</fullName>
    </customValue>
    <customValue>
        <fullName>icon_service_holiday_lighting</fullName>
    </customValue>
    <customValue>
        <fullName>icon_service_irrigation_inspection</fullName>
    </customValue>
    <customValue>
        <fullName>icon_service_lawn_mowing_economy</fullName>
    </customValue>
    <customValue>
        <fullName>icon_service_lawn_mowing_initial</fullName>
    </customValue>
    <customValue>
        <fullName>icon_service_lawn_mowing_premium</fullName>
    </customValue>
    <customValue>
        <fullName>icon_service_leaf_cleanup</fullName>
    </customValue>
    <customValue>
        <fullName>icon_service_mulch_installation</fullName>
    </customValue>
    <customValue>
        <fullName>icon_service_mulch_refresh</fullName>
    </customValue>
    <customValue>
        <fullName>icon_service_paint_walls</fullName>
    </customValue>
    <customValue>
        <fullName>icon_service_palm_trimming</fullName>
    </customValue>
    <masterLabel>Product Icons</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Service_Template_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AFM Weekly Lawncare</fullName>
    </customValue>
    <customValue>
        <fullName>AFM Bi-weekly Lawncare</fullName>
        <label>AFM Bi-weekly Landscaping</label>
    </customValue>
    <customValue>
        <fullName>AFM Monthly Lawncare</fullName>
    </customValue>
    <customValue>
        <fullName>AFM Weekly Cleaning</fullName>
    </customValue>
    <customValue>
        <fullName>AFM Bi-weekly Cleaning</fullName>
    </customValue>
    <customValue>
        <fullName>AFM Monthly Cleaning</fullName>
    </customValue>
    <customValue>
        <fullName>One-Time</fullName>
    </customValue>
    <customValue>
        <fullName>Custom</fullName>
    </customValue>
    <customValue>
        <fullName>MSR Premium Refresh</fullName>
    </customValue>
    <masterLabel>Service Template Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OrderFunnel_ProductUtilityHelper.cls
public with sharing class OrderFunnel_ProductUtilityHelper {
    private static Map<Id, OrderFunnel_Models.Product2Model> productModelMap = new Map<Id, OrderFunnel_Models.Product2Model>();
    private static String accountId;

    public static void buildProductModelMap(Set<Id> productIds, String accountId){
        if(accountId != accountId){
            accountId = accountId;
            productModelMap = new Map<Id, OrderFunnel_Models.Product2Model>();
        }else{
            productIds.removeAll(productModelMap.keySet());
        }

        if(productIds.isEmpty()){
            return;
        }

        List<Product2> products = [ SELECT  Id, Name, ProductCode, Display_Name__c, RecordType.Name, Description,
                                            Family, Merchandising_Tags__c, Netsuite_Item__c, SBQQ__TaxCode__c, Estimated_Effort_Coefficient__c,
                                            Product_Family__c, Product_Family__r.Name, Product_Family__r.External_ID__c, Product_Family__r.Color__c, Product_Family__r.Icon_Tag__c,
                                            Product_Family__r.Marketing_Description__c ,External_Id__c, Product_Photo_URL__c, Service_Template_Type__c
                                    FROM    Product2
                                    WHERE   Id IN :productIds OR External_ID__c IN: productIds ];

        set<String> setTemplateType = new set<String>();
        for(Product2 product: products){
            setTemplateType.add(product.Service_Template_Type__c);
        }

        Map<String, List<Service_Template__c>> mapTemplatesByType = new ServiceTemplateSelector().selectByType(setTemplateType);

        for(Product2 product: products){
            List<Service_Template__c> listTemplate = new List<Service_Template__c>();

            if (mapTemplatesByType.containsKey(product.Service_Template_Type__c)) {
                listTemplate = mapTemplatesByType.get(product.Service_Template_Type__c);
            }
            OrderFunnel_Models.Product2Model productModel = buildProductModel(product, listTemplate);
            productModelMap.put(product.Id, productModel);
            productModelMap.put(product.External_ID__c, productModel);
        }

        buildServiceTypes(productIds, accountId);
    }

    private static void buildServiceTypes(Set<Id> productIds, String accountId){
        List<Service_Type__c> serviceTypes = [  SELECT  Id, Name, Contractor_Description__c, Customer_Description__c,

                                                        (   SELECT  Id, Product__c, Product__r.Id, Product__r.Name, Product__r.ProductCode, Product__r.Display_Name__c,
                                                                    Product__r.RecordType.Name, Product__r.Description, Product__r.Family, Product__r.Merchandising_Tags__c,
                                                                    Product__r.Product_Family__c, Product__r.Product_Family__r.Name, Product__r.Product_Family__r.External_ID__c, Product__r.Product_Family__r.Color__c, Product__r.Product_Family__r.Icon_Tag__c,
                                                                    Product__r.Product_Family__r.Marketing_Description__c, Product__r.Netsuite_Item__c, Product__r.SBQQ__TaxCode__c, Product__r.External_ID__c, Product__r.Product_Photo_URL__c
                                                            FROM    Component_Services__r
                                                            WHERE   Product__c IN :productIds OR Product__r.External_ID__c IN: productIds),

                                                        (   SELECT  Id, Photo__c, Photo__r.Name, Photo__r.Sample_Photo__c, Photo__r.Instructional_Photo__c,
                                                                    Photo__r.Before_Service__c, Photo__r.Service_in_Action__c, Photo__r.After_Service__c
                                                            FROM    Photo_Set_Items__r
                                                            WHERE   Customer__c = null OR Customer__c = :accountId)
                                                FROM    Service_Type__c
                                                WHERE   Id IN
                                                        (   SELECT Service_Type__c
                                                            FROM Component_Service__c
                                                            WHERE Product__c IN :productIds OR Product__r.External_ID__c IN: productIds)
                                                ];
        for(Service_Type__c sType : serviceTypes){
            OrderFunnel_Models.ServiceTypeModel model = buildServiceTypeModel(sType);


            for(Component_Service__c component:sType.Component_Services__r){
                OrderFunnel_Models.Product2Model productModel = productModelMap.get(component.Product__c);
                if(productModel == null){
                    productModel = buildProductModel(component.Product__r, null);
                    productModelMap.put(component.Product__c, productModel);
                }
                productModel.ServiceTypes.add(model);
            }
        }
    }

    private static OrderFunnel_Models.Product2Model buildProductModel(Product2 product, List<Service_Template__c> serviceTemplates){
        OrderFunnel_Models.Product2Model model = new OrderFunnel_Models.Product2Model();
        model.Id = product.Id;
        model.externalId = product.External_ID__c;
        model.ProductName = product.Name;
        model.ProductCode = product.ProductCode;
        model.DisplayName = product.Display_Name__c;
        model.productPhotoURL = product.Product_Photo_URL__c;
        model.Type = product.RecordType.Name;
        model.Description = product.Description;
        model.Family = product?.Product_Family__r?.Name;
        model.iconTag = product?.Product_Family__r?.Icon_Tag__c;
        model.color = product?.Product_Family__r?.Color__c;
        model.MarketingDescription = product?.Product_Family__r?.Marketing_Description__c;
        model.MerchandisingTags = product.Merchandising_Tags__c;
        model.NetsuiteItem = product.Netsuite_Item__c;
        model.TaxCode = product.SBQQ__TaxCode__c;
        model.estimatedEffortMins = product.Estimated_Effort_Coefficient__c;

        if (product.Product_Family__c != null) {
            model.productFamily = new OrderFunnel_Models.ProductFamilyModel();
            model.productFamily.Id = product.Product_Family__c;
            model.productFamily.externalId = product.Product_Family__r.External_ID__c;
            model.productFamily.name = product.Product_Family__r.Name;    
        }
        
        // Added by Fran 07-12-2022 Product2 Api Task - Add Service Templates
        model.defaultServiceTemplate = product.Service_Template_Type__c;

        for (Service_Template__c item : serviceTemplates) {
            model.serviceTemplates.add(buildServiceTemplateModel(item));
        }
        // End. Fran

        return model;
    }

    // Added by Fran 07-12-2022 Product2 Api Task - Add Service Templates
    public static OrderFunnel_Models.ServiceTemplateModel buildServiceTemplateModel(Service_Template__c componentService){
        OrderFunnel_Models.ServiceTemplateModel serviceTemplateModel = new OrderFunnel_Models.ServiceTemplateModel();
        serviceTemplateModel.schedule = componentService.Service_Schedule__c;
        serviceTemplateModel.type = componentService.Service_Template_Type__c;
        serviceTemplateModel.zone = componentService.AFM_Zone__c;
        return serviceTemplateModel;
    }
    // End. Fran

    private static OrderFunnel_Models.ServiceTypeModel buildServiceTypeModel(Service_Type__c sType){
        OrderFunnel_Models.ServiceTypeModel model = new OrderFunnel_Models.ServiceTypeModel();
        model.Id = sType.Id;
        model.Name = sType.Name;
        model.ServiceCode = sType.Id;
        model.description.customer = sType.Customer_Description__c;
        model.description.contractor = sType.Contractor_Description__c;

        for(Photo_Set_Item__c photoSetItem : sType.Photo_Set_Items__r){
            model.PhotoSets.addAll(buildPhotoSetModels(photoSetItem.Photo__r));
        }

        return model;
    }

    private static List<OrderFunnel_Models.PhotoSetModel> buildPhotoSetModels(Photo__c photoSet){
        List<OrderFunnel_Models.PhotoSetModel> models = new List<OrderFunnel_Models.PhotoSetModel>();

        if(photoSet.Before_Service__c){
            models.add(buildPhotoSetModel(photoSet, 'BEFORE'));
        }
        if(photoSet.After_Service__c){
            models.add(buildPhotoSetModel(photoSet, 'AFTER'));
        }
        if(photoSet.Service_in_Action__c){
            models.add(buildPhotoSetModel(photoSet, 'SINGLE'));
        }

        return models;
    }

    private static OrderFunnel_Models.PhotoSetModel buildPhotoSetModel(Photo__c photoSet, String timing){
        OrderFunnel_Models.PhotoSetModel model = new OrderFunnel_Models.PhotoSetModel();
        model.PhotoId = photoSet.Id + '_' + timing;
        model.PhotoName = photoSet.Name;
        model.PhotoDefinitionId = photoSet.Id;
        model.PhotoDescription = photoSet.Name;
        model.PhotoExample = photoSet.Sample_Photo__c;
        model.PhotoInstruction = photoSet.Instructional_Photo__c;
        model.Timing = timing;
        return model;
    }


    public static OrderFunnel_Models.Product2Model getProductModel(String productId, String accountId){
        if(productModelMap == null){
            throw new API_Dispatcher.APIException(500, 'Product model map not initialized.');
        }

        //TODO Reinstate this
        // if(accountId != OrderFunnel_ProductUtilityHelper.accountId){
        //     throw new API_Dispatcher.APIException(500, 'Cross-customer product model access detected.');
        // }

        if(productModelMap.containsKey(productId) == false){
            throw new API_Dispatcher.APIException(404, 'Product model not found or initialized.');
        }
        return productModelMap.get(productId);
    }
}