force-app/main/default/objects/Funds_Adjustment_Request__c/Funds_Adjustment_Request__c.object-meta.xml
<CustomObject>
    <label>Funds Adjustment Request</label>
    <nameField>
        <displayFormat>FAR-{00000}</displayFormat>
        <label>Funds Adjustment Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Funds Adjustment Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Funds_Adjustment_Request__c/fields/Job_Id__c.field-meta.xml
<CustomField>
    <fullName>Job_Id__c</fullName>
    <label>Job Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Funds_Adjustment_Request__c/fields/Reason_for_Adjustment__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_Adjustment__c</fullName>
    <label>Reason for Adjustment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bid Task</fullName>
            </value>
            <value>
                <fullName>BPI Error</fullName>
            </value>
            <value>
                <fullName>Duplicate Charge</fullName>
            </value>
            <value>
                <fullName>Duplicate Service</fullName>
            </value>
            <value>
                <fullName>Fix it Task</fullName>
            </value>
            <value>
                <fullName>Incorrect Pricing/Incorrect Tracing</fullName>
            </value>
            <value>
                <fullName>Incorrect Snow Depth</fullName>
            </value>
            <value>
                <fullName>Insurance Claim</fullName>
            </value>
            <value>
                <fullName>No Work Done/ Partial Work Completed</fullName>
            </value>
            <value>
                <fullName>OGF</fullName>
            </value>
            <value>
                <fullName>Retention Effort</fullName>
            </value>
            <value>
                <fullName>RO Error</fullName>
            </value>
            <value>
                <fullName>Seasonality Error</fullName>
            </value>
            <value>
                <fullName>Serviced After Stop Request</fullName>
            </value>
            <value>
                <fullName>Serviced Too Soon</fullName>
            </value>
            <value>
                <fullName>TE Error - Client Comp</fullName>
            </value>
            <value>
                <fullName>TE Good Faith Discount</fullName>
                <label>TE Good Faith Discount - (TE Not at Fault)</label>
            </value>
            <value>
                <fullName>Wrong Property Serviced</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Funds_Adjustment_Request__c/fields/Request_Status__c.field-meta.xml
<CustomField>
    <fullName>Request_Status__c</fullName>
    <label>Request Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Request Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FundsAdjustmentRequest_Test.cls
@isTest
public with sharing class FundsAdjustmentRequest_Test {
    
    @TestSetup
    static void makeData(){
        Funds_Adjustment_Request__c newRequest = new Funds_Adjustment_Request__c();
        newRequest.Job_Id__c = '1234';
        newRequest.Reason_for_Adjustment__c = 'Duplicate Charge';
        newRequest.Request_Status__c = FundsAdjustmentRequestSelector.RequestStatus_New;
        insert newRequest;    
    }

    @IsTest
    static void validateDuplicate(){
        
        Test.startTest();
            
            Funds_Adjustment_Request__c newRequest2 = new Funds_Adjustment_Request__c();
            newRequest2.Job_Id__c = '1234';
            newRequest2.Reason_for_Adjustment__c = 'Duplicate Charge';
            insert newRequest2;

        Test.stopTest();
        
    }
}